# Generated by Django 3.0 on 2020-03-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='drive_route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist_km', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('time_it', models.CharField(max_length=30)),
            ],
        ),
    ]
