# Generated by Django 3.0 on 2020-03-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20200328_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='fname',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='myuser',
            name='lname',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='myuser',
            name='password2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
