# Generated by Django 3.0 on 2020-03-28 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20200328_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='password2',
            new_name='password',
        ),
    ]
