# Generated by Django 3.0 on 2020-03-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_myuser_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, unique=True)),
                ('password', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
