# Generated by Django 3.0 on 2020-03-28 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200328_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='donator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Donator'),
        ),
        migrations.AddField(
            model_name='donate',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Item'),
        ),
    ]
