# Generated by Django 3.0 on 2020-03-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providr_posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='slug',
            field=models.SlugField(default='hello'),
            preserve_default=False,
        ),
    ]
