# Generated by Django 3.0 on 2020-03-29 04:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('providr_posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpost',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 29, 4, 14, 26, 299022)),
        ),
        migrations.AddField(
            model_name='userpost',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2020, 3, 29, 4, 14, 43, 352523, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userpost',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
