# Generated by Django 3.0 on 2020-03-29 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providr_posts', '0003_auto_20200329_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 29, 6, 36, 5, 623435)),
        ),
    ]
