# Generated by Django 3.0 on 2020-03-28 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('providr_posts', '0003_auto_20200328_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
